version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: teste
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
