replicaCount: 1

image:
  tag: dev

service:
  type: NodePort
  port: 8080

resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1"

ingress:
  enabled: true
  hosts:
    - host: dev.myapp.local
      paths:
        - /
