replicaCount: 1

image:
  repository: myrepo/myimage
  tag: latest

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

ingress:
  enabled: false
