apiVersion: v1
kind: Service
metadata:
  name: my-fastapi-service
spec:
  type: NodePort
  selector:
    app: my-fastapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
