name: CI Workflow
 
on: [pull_request, push]
 
jobs:
  ci-work:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
 
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
 
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_NAME}}
          password: ${{secrets.DOCKER_SENHA}}
 
      - name: Push docker image
        uses: docker/build-push-action@v6
        with:
          context: .    
          push: true
          tags: ${{secrets.DOCKER_NAME}}/fast_api_latest   
