name: CI Workflow # nome do workflow
 
on: [pull_request, push] # quando ele vai ser acionado
 
jobs:  # aqui o que ele vai fazer
  ci-work:
    runs-on: ubuntu-latest  # git vai alocar uma VM ubuntu pra rodar os comando abaixo
 
    steps:
      - uses: actions/checkout@v3  # copia teu repositorio pra VM do git
 
      - name: Set up Python
        uses: actions/setup-python@v2  # seta ambiente python pra poder rodar o fastapi q é pyhton
        with:
          python-version: '3.12'
 
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3  # vai implementar o docker se n me engano
 
      - name: Docker login
        uses: docker/login-action@v3  # vai realizar o login do teu user do dockerhub pra poder enviar a imagem pro registri dele
        with:
          username: ${{secrets.DOCKER_NAME}}   # variavel de ambiente com o nome do user do dockerhub
          password: ${{secrets.DOCKER_PASSWORD}}  # variavel de ambiente com a tua senha do dockerhub
 
      - name: Push docker image
        uses: docker/build-push-action@v6  # aqui ele vai builda a imagem e manda ela pro dockerhub
        with:
          context: .    
          push: true
          tags: ${{secrets.DOCKER_NAME}}/fast_api_latest
